In [10]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
print(a.dot(b))
print(b.dot(a))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [11]:
a = a + np.sum(a)
print(a)

[[11 12]
 [13 14]]
